### ISSUE TITLE
the 1.27.4 patch does not seem to be working as expected.

### ISSUE THREAD

**Issue by Wildcarde** [mediawiki4intranet/IntraACL#91]
You get the following error when attempting to apply the 1.27.4 patch:
```
A database query error has occurred.
Query: call `create_parent_pages`() 

Function: DatabaseBase::sourceFile( /opt/brody1274wiki/extensions/IntraACL/includes/../storage/intraacl-functions-mysql.sql )
Error: 1005 Can't create table 'brody127wiki.parent_pages' (errno: 150) (localhost)

Creating IntraACL 'Permission denied' page...PHP Fatal error:  Uncaught Error: Call to undefined method Message::getText() in /opt/brody1274wiki/includes/parser/Parser.php:3694
Stack trace:
#0 /opt/brody1274wiki/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(Array, Object(PPFrame_DOM))
#1 /opt/brody1274wiki/includes/parser/Parser.php(3402): PPFrame_DOM->expand(Object(DOMElement), 0)
#2 /opt/brody1274wiki/includes/parser/Parser.php(1261): Parser->replaceVariables('{{:MediaWiki:ha...')
#3 /opt/brody1274wiki/includes/parser/Parser.php(452): Parser->internalParse('{{:MediaWiki:ha...')
#4 /opt/brody1274wiki/includes/content/WikitextContent.php(331): Parser->parse('{{:MediaWiki:ha...', Object(Title), Object(ParserOptions), true, true, NULL)
#5 /opt/brody1274wiki/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Object(Title), NULL, Object(ParserOptions), true, Object(ParserOutput))
#6 /opt/brody1274wiki/includes/page/WikiPage.php(2110): AbstractContent->getParserOutput(Object(Title), NULL, Object(ParserOptions))
#7 /opt/brody12 in /opt/brody1274wiki/includes/parser/Parser.php on line 3694
```

**Comment by Wildcarde** [comment]
I've managed to force this by updating the parser/Parser.php file to call `text()` instead of `getText()` at link 3694, the sql issue was resolved by adding `engine=myisam` to the end.
